- variables: variables in ansible
  hosts: mongodb
  # this is play level variable, map
  vars:
   COURSE: DevOPS
   TRAINER: Siva
   DURATION: 110HRS
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: Hello, I am Learning Ansible
  - name: print variable
    ansible.builtin.debug:
      msg: "Hello, I am learning {{COURSE}}, trainer is {{Siva}}, Duration is {{110HRS}}"
