- name: testing variable precedencie
  hosts: mongodb
  vars: 
    NAME: Nageswari-play
  # vars_files:
  # - variables.yaml
  # vars_prompt:
  # - name: NAME
    prompt: please enter your trainer name
    private: false
  tasks:
  - name: variables at task level 
    # vars: 
    #  NAME: Nageswari-task
    ansible.builtin.debug: 
     msg: "Trainer name is: {{NAME}}"

 # 1. command line variable
 # 2. task level
 # 3. vars_files 
 # 4. vars_prompt