- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
    ansible.builtin.debug:
    register: output
    ignore_errors: true
  - name: print the command output
    ansible.builtin.debug:
      msg: "output is: {{output}}"
  - name: print exit status
    ansible.builtin.debug:
      msg: "{{output.rc}}"
  - name: create user roboshop
    become: true
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0             
